# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunTimeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 4.4.1'
  pod 'Masonry', '~> 1.1.0'

end
